### ISSUE TITLE
standard-engine

### ISSUE THREAD

**Issue by tunnckoCore** [standards/meta#2]
- To be more general in first place
- To be in `standars/engine`
- Using (passing to it) different linters for each of the style standards. 
- It is possible to transfer `flet/standard-engine` here or rewrite it? 
- Without CLI in it, it would be core factory mechanism for loading lint configs and linting #3

**Comment by leog** [comment]
@tunnckoCore is this what the meta standard is now? please advice so we can close it and start fresh with new relevant issues to cover new standards going with the new process.

**Comment by tunnckoCore** [comment]
No. The whole idea around was a bit different, but anyway ;d So yea, this issue is outdated, so we can close.
