### ISSUE TITLE
`feross/standard` pkg and `standards/standard` CLI

### ISSUE THREAD

**Issue by tunnckoCore** [standards/meta#3]
- can be transferred here
- i think it should be rewritten
- it will continue to have backward compatibility
- it would support flags for
  - javascript (gfm) code blocks in md files (maybe only READMEs?)
  - checking against `standards/readme` standard for README code style
  - `semistandard` case, cuz it is just overriding of one prop of config that is passed to eslint
  - using the other style standards from the org (assuming which to use on per extension basis?)
  - using `-u` flag for `.use`ing other standards and passing them to `standards/engine`?
  - and all current flags
  - support for different reporters with `-R`
- it would be just CLI
- `eslint-(semi)standard-config` (aka shareable configs) to be in org
- `standards/js` maybe core of `standards/standard` backward compatible, just for js, lightweight?
  - maybe it would be my experimental implementation of `feross/standard` using my `glob-fs` and `micromatch` instead of `node-glob` + `minimatch` implementation when it is almost rdy and when whole stack of github.com/vinyljs stack is done

TBC...

**Comment by leog** [comment]
@tunnckoCore closing in favor of promoting the javascript project standard which will cover the possibility of including standardjs
